### PR TITLE
Recursive domain lookup

### PR DESCRIPTION
**Pull request by doolo**
Summary of this PR:
- A lot of commons on many important files to help people understand the code
- Implement recursive domain lookup for clients
- Implement recursive domain query for relays
- Explicitly write out the rule for POLICY_VANILLA_PROXY
- Add new docs to help people with testing and development
- Update dependencies for one-click-deployment script

### CODE REVIEW

**Comment by srxzr** [comment]
This is not a good implementation. First, define and assign the regex, then put it in the cache. 
 var regex
     globalRegexCache[this.subdomain] = regex
    // check if this.subdomain really exist
    if(!this.subdomain){
      regex = globalRegexCache['SUB_FOR_UNDEFINED']
    }
    else{
      regex = globalRegexCache[this.subdomain]
      if (regex) {
        return regex
      }
      else{
        regex = new RegExp('^' + this.subdomain + '$')
        globalRegexCache[this.subdomain] = regex
      }
    }

**Comment by doolo** [comment]
The recursive domain lookup (mentioned in: https://github.com/SPIN-UMass/MassBrowser/issues/105) passes my primary test: https://github.com/SPIN-UMass/MassBrowser/pull/104/commits/18393f271658268910a7f0f0d805423f89bd3eec

Here is the output:
```
debug: New socks connection to mewmemew.www.youtube.com:443 using policy 'yaler_proxy'
Function call Domain.find( mewmemew.www.youtube.com ) returns:  []
Function call Domain.find( www.youtube.com ) returns:  []
Function call Domain.find( youtube.com ) returns:  [ Domain {
    name: 'youtube.com',
    subdomain: '.*',
    blockedRegions: null,
    website: 'omvnC5pv-68',
    cdn: null,
    ssl: true,
    _regex_cache: null,
    _schema: 
     [ 'id',
       'name',
       'subdomain',
       'blockedRegions',
       'website',
       'cdn',
       'ssl' ],
    model: [Function: Domain],
    _new_instance: false,
    _cached_transformer: null,
    id: 'ormge0SE_nY',
    _id: 'aJj8jRV2TE07r1Z0' } ]
Returns the final matching domain object:  Domain {
  name: 'youtube.com',
  subdomain: '.*',
  blockedRegions: null,
  website: 'omvnC5pv-68',
  cdn: null,
  ssl: true,
  _regex_cache: null,
  _schema: 
   [ 'id',
     'name',
     'subdomain',
     'blockedRegions',
     'website',
     'cdn',
     'ssl' ],
  model: [Function: Domain],
  _new_instance: false,
  _cached_transformer: null,
  id: 'ormge0SE_nY',
  _id: 'aJj8jRV2TE07r1Z0' }
debug: Assigning session for mewmemew.www.youtube.com of category Video Streaming
```

Note that the test above covers the case of non-existing domain name.

Would you please help to review my code, @srxzr ?

Thank you very much for your help! :)

**Comment by srxzr** [comment]
Please implement the same algorithm for the relay find domain as well

**Comment by doolo** [comment]
Thank you for reminding me! Done!

**Pull request merged**
